spring:
  application:
    name: das-common-config #配置中心服务名称
  profiles:
    active: native #配置中心配置文件方式 git/maven/native(本地)
  cloud:
    bus:
      trace:
        enabled: true #跟踪总线事件
    config:
      server:
        native:
          searchLocations: classpath:/config-repo/ #配置文件读取路径
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  security:
    enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/ #注册中心地址
    healthcheck:
      enabled: true #启用健康检查
  lease-expiration-duration-in-seconds: 90
  instance:
    lease-renewal-interval-in-seconds: 30
server:
  port: 8888 #配置中心端口号