management:
  security:
    enabled: false #刷新时关闭安全验证
spring:
  cloud:
    bus:
      trace:
        enabled: true #开启消息跟踪
spring:
  rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
