server:
  port: 8500 #网关项目端口号
spring:
  application:
    name: das-common-gateway #网关项目名称
# 不配置下面的话，代理访问会以service-id来访问，例如：http://localhost:8500/das-system-api/get
zuul:
  routes:
    producer:
      path: /api/** #网关路由请求地址
      serviceId: das-system-api #网关路由调用服务