spring:
  application:
    name: das-system-api #系统基础服务api项目名称
  datasource:
    url: jdbc:mysql://localhost:3306/test #数据库地址
    username: root #数据库用户
    password: 123456 #数据库密码
    driver-class-name: com.mysql.jdbc.Driver #mysql驱动
  zipkin:
      base-url: http://localhost:9005 #分布式链路跟踪服务地址
  sleuth:
    sampler:
      percentage: 1.0 #分布式链路跟踪采样比例
server:
  port: 9001 #系统基础服务api项目端口号
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml #mybatis配置文件
  mapper-locations: classpath:mybatis/mapper/*.xml #mybatis扫描路径及文件类型